version: 2.1.0.{build}
image: Visual Studio 2019
skip_tags: true
skip_branch_with_pr: true
skip_commits:
  files:
    - .github/*
    - .paket/*
    - '**/*.md'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(appveyor_build_version)'
  package_version: '$(appveyor_build_version)'
  assembly_version: '$(appveyor_build_version)'
  file_version: '$(appveyor_build_version)'
  informational_version: '$(appveyor_build_version)'
build_script:
- cmd: dotnet publish src\PaketSorter.sln --runtime win-x64 --configuration Release /p:PublishSingleFile=true /p:DebugType=None
test: off
artifacts:
- path: src\PaketSorter\bin\Release\netcoreapp3.0\win-x64\publish\PaketSorter.exe
  name: PaketSorter.exe
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: v$(appveyor_build_version)
  description: Release v$(appveyor_build_version)
  auth_token:
    secure: g+iWKsE2NIl0nbHRppdKG9viG1Drk5x6U++4dXtMfM9FLyOFqaRafq6qKpkyO9x7
  repository: BlythMeister/PaketSorter
  artifact: src\PaketSorter\bin\Release\netcoreapp3.0\win-x64\publish\PaketSorter.exe
  on:
    branch: master
