version: 1.0.{build}
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(appveyor_build_version)'
  package_version: '$(appveyor_build_version)'
  assembly_version: '$(appveyor_build_version)'
  file_version: '$(appveyor_build_version)'
  informational_version: '$(appveyor_build_version)'
build_script:
- cmd: dotnet build src\PaketSorter.sln --runtime win-x64 --configuration Release
test: off
artifacts:
- path: src\PaketSorter\bin\Release\netcoreapp2.2\win-x64
  name: App-$(appveyor_build_version)
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: v$(appveyor_build_version)
  description: Release v$(appveyor_build_version)
  auth_token:
    secure: g+iWKsE2NIl0nbHRppdKG9viG1Drk5x6U++4dXtMfM9FLyOFqaRafq6qKpkyO9x7
  repository: BlythMeister/PaketSorter
  artifact: src\PaketSorter\bin\Release\netcoreapp2.2\App-$(appveyor_build_version).zip
  on:
    branch: master